name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up test environment
      run: |
        mkdir -p ~/bin
        mkdir -p ~/.claude/commands
        
    - name: Install gsum
      run: make install
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install MCP server dependencies
      run: cd mcp-server && npm install
      
    - name: Verify installation
      run: |
        ls -la ~/bin/smart-gsum
        ls -la ~/bin/gsummarize-wrapper
        ls -la ~/.claude/commands/gsum.md
        
    - name: Run MCP server tests
      run: cd mcp-server && npm test
        
    - name: Run integration tests
      run: make test