name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up test environment
      run: |
        mkdir -p ~/bin
        mkdir -p ~/.claude/commands
        
    - name: Install gsum
      run: make install
      
    - name: Verify installation
      run: |
        ls -la ~/bin/smart-gsum
        ls -la ~/bin/gsummarize-wrapper
        ls -la ~/.claude/commands/gsum.md
        
    - name: Run tests
      run: make test